-------------------------- Docker File ----------------

1. Docker files is used to create a docker image ti has a steps to create a docker iages for
   our application.

2. Dockerfile --> create a file name in WRKDIR.

3. FROM --> used to create a base images means that iamages from the docker hub.

4. COPY source destination --> to copy file

5. RUN command --> runs command in docker images

6. WORKDIR path --> changes the current working directory in the container

7. CMD ['command'] --> runs internal commands

8. .dockerignore --> igoners the file and folders while copying

9. docker build -t tagname dockerFile path --> creates an docker image with the respective 
   dockerFile
